apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-ingress
spec:
  rules:
  - host:
    http:
      paths:
      - path: /webserver
        backend:
          service:
            name: webserver-service
            port:
              number: 5000
